site_name: Workflows
theme:
  name: material
  palette:
    primary: blue grey
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html
docs_dir: docs-src
site_dir: docs