name: CI
on:
  workflow_call:
    inputs:
      go-version: 
        required: false
        type: number
        default: 1.16
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: Go vet
        run: make vet
      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          skip-pkg-cache: true
          skip-go-installation: true
      - name: Go fmt check
        run: make fmt-check
      - name: Go test
        run: make test
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov