name: CI
on:
  workflow_call:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Go vet
        run: make vet
      - name: Go lint
        run: make lint
      - name: Go fmt check
        run: make fmt-check
      - name: Go test
        run: make test
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov