name: Release Homelab
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_name: 
        required: true
        type: string
      deployment:
        required: true
        type: string
      container:
        required: true
        type: string
      namespace:
        required: true
        type: string
      version:
        required: true
        type: string
      config_path:
        required: true
        type: string
    secrets:
      kube_config:
        required: true
      username:
        required: true
      password:
        required: true
jobs:
 release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      - name: Setup Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.kube_config }}
      - name: Deploy Application
        run: kubectl apply -f ${{ inputs.config_path }}
      - name: Set Image
        run: kubectl set image deployments/${{ inputs.deployment }} -n ${{ inputs.namespace }} ${{ inputs.container }}=${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version}}
