name: Release Homelab
on:
  workflow_call:
    # inputs:
      # registry:
      #   required: true
      #   type: string
      # image_name: 
      #   required: true
      #   type: string
      # deployment:
      #   required: true
      #   type: string
      # container:
      #   required: true
      #   type: string
      # namespace:
      #   required: true
      #   type: string
    secrets:
      # kube_config:
      #   required: true
      # username:
      #   required: true
      # password:
      #   required: true
      token:
        required: true
jobs:
 release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.token }}
          changelog-file: true
          update-file: VERSION
      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ inputs.registry }}
      #     username: ${{ secrets.username }}
      #     password: ${{ secrets.password }}
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ inputs.registry }}/${{ inputs.image_name }}
      #     tags: |
      #       type=sha
      #       type=raw,v${{ steps.package-version.outputs.current-version}}
      #     flavor: |
      #       latest=true
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      # - name: Install Kubectl
      #   uses: azure/setup-kubectl@v1
      # - name: Setup Context
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.kube_config }}
      # - name: Deploy Application
      #   run: kubectl apply -f homelab.yaml
      # - name: Set Image
      #   run: kubectl set image deployments/${{ inputs.deployment }} -n ${{ inputs.namespace }} ${{ inputs.container }}=${{ inputs.registry }}/${{ inputs.image_name }}:v${{ steps.package-version.outputs.current-version}}
